name: Simple-test-pipline


on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update jar version to 1.0.1
        run: mvn versions:set -DnewVersion=1.0.1
        
      - name: Build the project
        run: mvn -B package --file pom.xml